// <auto-generated />
using System;
using BusinessParkCompaniesManagement.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessParkCompaniesManagement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813121454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByAdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminUserId");

                    b.HasIndex("SectorId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ComplaintTypeId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.ComplaintType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComplaintTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "مشكلة صيانة",
                            NameEn = "Maintenance Issue"
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "مشكلة إنترنت / شبكة",
                            NameEn = "Internet / Network Issue"
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "مشكلة كهرباء",
                            NameEn = "Electricity Issue"
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "مشكلة إمدادات المياه",
                            NameEn = "Water Supply Issue"
                        },
                        new
                        {
                            Id = 5,
                            NameAr = "مشكلة تكييف الهواء",
                            NameEn = "HVAC / Air Conditioning Issue"
                        },
                        new
                        {
                            Id = 6,
                            NameAr = "مشكلة مواقف السيارات",
                            NameEn = "Parking Issue"
                        },
                        new
                        {
                            Id = 7,
                            NameAr = "النظافة والصرف الصحي",
                            NameEn = "Cleanliness & Sanitation"
                        },
                        new
                        {
                            Id = 8,
                            NameAr = "مخاوف أمنية",
                            NameEn = "Security Concern"
                        },
                        new
                        {
                            Id = 9,
                            NameAr = "شكوى ضوضاء",
                            NameEn = "Noise Complaint"
                        },
                        new
                        {
                            Id = 10,
                            NameAr = "اقتراح عام للتحسين",
                            NameEn = "General Suggestion for Improvement"
                        });
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "تكنولوجيا المعلومات",
                            NameEn = "Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "الاتصالات",
                            NameEn = "Telecommunications"
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "التجارة والبيع بالتجزئة",
                            NameEn = "Trade & Retail"
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "الصناعة",
                            NameEn = "Manufacturing"
                        },
                        new
                        {
                            Id = 5,
                            NameAr = "الخدمات المالية",
                            NameEn = "Financial Services"
                        },
                        new
                        {
                            Id = 6,
                            NameAr = "الرعاية الصحية",
                            NameEn = "Healthcare"
                        },
                        new
                        {
                            Id = 7,
                            NameAr = "التعليم",
                            NameEn = "Education"
                        },
                        new
                        {
                            Id = 8,
                            NameAr = "الخدمات اللوجستية والنقل",
                            NameEn = "Logistics & Transportation"
                        },
                        new
                        {
                            Id = 9,
                            NameAr = "الخدمات الاستشارية",
                            NameEn = "Consulting Services"
                        },
                        new
                        {
                            Id = 10,
                            NameAr = "أخرى",
                            NameEn = "Other"
                        });
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.Company", b =>
                {
                    b.HasOne("BusinessParkCompaniesManagement.Server.Models.Entities.AdminUser", "CreatedByAdminUser")
                        .WithMany("Companies")
                        .HasForeignKey("CreatedByAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessParkCompaniesManagement.Server.Models.Entities.Sector", "Sector")
                        .WithMany("Companies")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAdminUser");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.Complaint", b =>
                {
                    b.HasOne("BusinessParkCompaniesManagement.Server.Models.Entities.Company", "Company")
                        .WithMany("Complaints")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessParkCompaniesManagement.Server.Models.Entities.ComplaintType", "ComplaintType")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ComplaintType");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.AdminUser", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.Company", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.ComplaintType", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("BusinessParkCompaniesManagement.Server.Models.Entities.Sector", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
